-- 잊기 전에 한 번 더 정답

-- 9-1
SELECT E.JOB, E.EMPNO, E.ENAME, E.SAL, E.DEPTNO, D.DNAME
  FROM EMP E, DEPT D
 WHERE E.DEPTNO = D.DEPTNO
   AND JOB = (SELECT JOB
                FROM EMP
               WHERE ENAME = 'ALLEN'); 

-- 9-2
SELECT E.EMPNO, E.ENAME, D.DNAME, E.HIREDATE, D.LOC, E.SAL, S.GRADE
  FROM EMP E, DEPT D, SALGRADE S
 WHERE E.DEPTNO = D.DEPTNO
   AND E.SAL BETWEEN S.LOSAL AND S.HISAL
   AND SAL > (SELECT AVG(SAL)
                FROM EMP)
ORDER BY E.SAL DESC, E.EMPNO; 

-- 9-3
SELECT E.EMPNO, E.ENAME, E.JOB, E.DEPTNO, D.DNAME, D.LOC
  FROM EMP E, DEPT D
 WHERE E.DEPTNO = D.DEPTNO
   AND E.DEPTNO = 10
   AND JOB NOT IN (SELECT DISTINCT JOB
                     FROM EMP
                    WHERE DEPTNO = 30); 

-- 9-4
-- 다중행 함수 사용하지 않는 방법
SELECT E.EMPNO, E.ENAME, E.SAL, S.GRADE
  FROM EMP E, SALGRADE S
 WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
   AND SAL > (SELECT MAX(SAL)
                FROM EMP
               WHERE JOB = 'SALESMAN')
ORDER BY E.EMPNO; 

--다중행 함수 사용하는 방법
SELECT E.EMPNO, E.ENAME, E.SAL, S.GRADE
  FROM EMP E, SALGRADE S
 WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
   AND SAL > ALL (SELECT DISTINCT SAL
                    FROM EMP
                   WHERE JOB = 'SALESMAN')
ORDER BY E.EMPNO;



----------------------------------------------------------------------------------------------------

-- 서브쿼리


-- 1.
SELECT JOB, EMPNO, ENAME, SAL, D.DEPTNO, DNAME
FROM EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO
WHERE JOB = (SELECT JOB FROM EMP WHERE ENAME = 'ALLEN')

-- 2.
SELECT E.EMPNO, E.ENAME, D.DNAME, E.HIREDATE, D.LOC, E.SAL, S.GRADE
FROM EMP E
JOIN DEPT D
     ON E.DEPTNO = D.DEPTNO
JOIN SALGRADE S
ON E.SAL BETWEEN S.LOSAL AND S.HISAL
WHERE SAL > (SELECT AVG(SAL) FROM EMP)

-- 3
SELECT EMPNO, ENAME, JOB, D.DEPTNO, DNAME, LOC
FROM EMP E
JOIN DEPT D ON E.DEPTNO = D.DEPTNO
WHERE E.DEPTNO = 10 AND E.JOB NOT IN (SELECT JOB FROM EMP WHERE DEPTNO=30)


-- 4
/*
 JOB이 'SALESMAN'인 사람들의 최고 급여보다 높은 급여를 바는 사원들의 사원 정보, 급여 등급정보

 예시 출력
 EMPNO ENAME SAL GRADE
 7566  JONES 2975 4
 */


SELECT JOB, EMPNO, ENAME, ROUND(SAL,0), DEPT.DEPTNO, DNAME
FROM EMP JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
WHERE JOB = (SELECT JOB FROM EMP WHERE ENAME = 'ALLEN')


SELECT EMPNO, ENAME, DNAME, HIREDATE, LOC, ROUND(SAL,1) AS SAL, GRADE
FROM EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO
JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
WHERE SAL > (SELECT AVG(SAL) FROM EMP )
ORDER BY SAL DESC, EMPNO ASC

WITH AVG_SAL_CTE AS (
    SELECT AVG(SAL) AS AVG_SAL
    FROM EMP
)
SELECT E.EMPNO,
       E.ENAME,
       D.DNAME,
       E.HIREDATE,
       D.LOC,
       ROUND(E.SAL,1) AS SAL,
       S.GRADE
FROM EMP E
    JOIN DEPT D ON E.DEPTNO = D.DEPTNO
    JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
    CROSS JOIN AVG_SAL_CTE
WHERE SAL > (AVG_SAL_CTE.AVG_SAL)
ORDER BY SAL DESC, EMPNO ASC

-- 3.
SELECT E.EMPNO,E.ENAME, E.JOB, D.DEPTNO, D.DNAME, D.LOC
FROM EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO
WHERE D.DEPTNO = 10 AND E.JOB NOT IN (SELECT JOB FROM EMP WHERE DEPTNO=30)

-- 4.
SELECT E.EMPNO,
       E.ENAME,
       ROUND(E.SAL,1) AS SAL,
       S.GRADE
FROM EMP E JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
WHERE E.SAL > (SELECT MAX(SAL) FROM EMP WHERE JOB='SALESMAN')
ORDER BY E.EMPNO ASC