-- 잊기 전에 한 번 더 정답

-- 7-1
SELECT DEPTNO,
       TRUNC(AVG(SAL)) AS AVG_SAL,
       MAX(SAL) AS MAX_SAL,
       MIN(SAL) AS MIN_SAL,
       COUNT(*) AS CNT
  FROM EMP
GROUP BY DEPTNO; 

-- 7-2
SELECT JOB,
       COUNT(*)
  FROM EMP
GROUP BY JOB
HAVING COUNT(*) >= 3; 

-- 7-3
SELECT TO_CHAR(HIREDATE, 'YYYY') AS HIRE_YEAR,
       DEPTNO,
       COUNT(*) AS CNT
  FROM EMP
GROUP BY TO_CHAR(HIREDATE, 'YYYY'), DEPTNO; 

-- 7-4
SELECT NVL2(COMM, 'O', 'X') AS EXIST_COMM,
       COUNT(*) AS CNT
  FROM EMP
GROUP BY NVL2(COMM, 'O', 'X'); 

-- 7-5
SELECT DEPTNO,
       TO_CHAR(HIREDATE, 'YYYY') AS HIRE_YEAR,
       COUNT(*) AS CNT,
       MAX(SAL) AS MAX_SAL,
       SUM(SAL) AS SUM_SAL,
       AVG(SAL) AS AVG_SAL
  FROM EMP
GROUP BY ROLLUP(DEPTNO, TO_CHAR(HIREDATE, 'YYYY'));

----------------------------------------------------------------------------------------

/*
 다중행 함수
 */

SELECT COUNT(COMM)
FROM EMP;

SELECT DEPTNO, AVG(SAL) AS AVG_SAL
FROM EMP GROUP BY DEPTNO;


SELECT AVG(SAL) FROM EMP;

SELECT AVG(SAL) FROM EMP GROUP BY DEPTNO;

SELECT DEPTNO, JOB, AVG(SAL) AS AVG_SAL
FROM EMP
GROUP BY DEPTNO, JOB
HAVING AVG(SAL) >= 2000
ORDER BY DEPTNO, JOB;


SELECT DEPTNO, JOB, AVG(SAL)
FROM EMP
GROUP BY DEPTNO, JOB
HAVING AVG(SAL) >= 500
ORDER BY DEPTNO, JOB


SELECT DEPTNO, JOB, COUNT(*), MAX(SAL), SUM(SAL), AVG(SAL)
FROM EMP
GROUP BY ROLLUP(DEPTNO, JOB);

SELECT ENAME FROM EMP WHERE DEPTNO = 10;

--
SELECT DEPTNO,
       LISTAGG(ENAME, ', ')
WITHIN GROUP(ORDER BY SAL DESC) AS ENAMES
FROM EMP
GROUP BY DEPTNO;

--
SELECT DEPTNO, ENAME
FROM EMP
GROUP BY DEPTNO;

SELECT DEPTNO, JOB, MAX(SAL) AS MAX
FROM EMP
GROUP BY DEPTNO, JOB
ORDER BY DEPTNO, JOB;

-- PIVOT 출력
SELECT *
    FROM(SELECT DEPTNO, JOB, SAL
         FROM EMP)
    PIVOT (MAX(SAL)
        FOR DEPTNO IN (10,20,30)
        )
ORDER BY JOB;


SELECT DEPTNO, TRUNC(AVG(SAL),0) AS AVG_SAL, MAX(SAL) AS MAX_SAL, MIN(SAL) AS MIN_SAL, COUNT(*) AS CNT
FROM EMP
GROUP BY DEPTNO

SELECT JOB, COUNT(*)
FROM EMP
GROUP BY JOB
HAVING COUNT(*) >= 3

-- 3.
SELECT TO_CHAR(HIREDATE,'YYYY') AS HIRE_YEAR,
       DEPTNO,
       COUNT(*) AS CNT FROM EMP
GROUP BY DEPTNO, TO_CHAR(HIREDATE,'YYYY')
ORDER BY TO_CHAR(HIREDATE,'YYYY') DESC;

SELECT NVL2(COMM, 'O', 'X') AS EXIST_COMM,
       COUNT(*) AS CNT
FROM EMP
GROUP BY NVL2(COMM, 'O', 'X');

-- 5.
SELECT DEPTNO, TO_CHAR(HIREDATE, 'YYYY') AS HIRE_YEAR,
       COUNT(*) AS CNT,
       MAX(SAL) AS MAX_SAL,
       SUM(SAL) AS SUM_SAL,
       AVG(SAL) AS AVG_SAL
FROM EMP
GROUP BY ROLLUP(DEPTNO, TO_CHAR(HIREDATE, 'YYYY'));